<a href="https://colab.research.google.com/github/armeennadeem197/numpy-task/blob/main/Numpy_task_1_to_5_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>






Armeen 867436


#Practice Tasks

## Task 1

Create this array:

```
10, 20, 30, 40, 50
```

Find:

- Sum
- Average
- Maximum
- Minimum

In [ ]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print("Array:", numbers)

print("Sum:", np.sum(numbers))
print("Average:", np.mean(numbers))
print("Maximum:", np.max(numbers))
print("Minimum:", np.min(numbers))

Array: [10 20 30 40 50]
Sum: 150
Average: 30.0
Maximum: 50
Minimum: 10


## Task 2

Create this array:

```
45, 80, 30, 90, 55, 20
```

Display only the values greater than or equal to `50`.

In [ ]:
import numpy as np

marks = np.array([45, 80, 30, 90, 55, 20])

passed = marks[marks >= 50]

print("Passed Marks:", passed)

Passed Marks: [80 90 55]


## Task 3

Create this array:

```
1, 2, 3, 4, 5, 6
```

Change it into:

```
2 rows
3 columns
```

In [ ]:
import numpy as np

numbers = np.array([1, 2, 3, 4, 5, 6])

new_array = numbers.reshape(2,3)

print(new_array)

[[1 2 3]
 [4 5 6]]


## Task 4

Generate `10` random marks between `40` and `100`.

Then find:

- Average
- Highest marks
- Lowest marks


In [ ]:
import numpy as np

marks = np.random.randint(40, 101, 10)

print("Random Marks:", marks)

print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))

Random Marks: [49 58 92 89 91 90 55 75 73 71]
Average: 74.3
Highest: 92
Lowest: 49


## Task 5

Create this marks array:

```
35, 67, 89, 45, 90, 22, 70, 58
```

Passing marks are `50`.

Find:

- Passed marks
- Failed marks
- Number of passed students
- Number of failed students

In [ ]:
import numpy as np

marks = np.array([35, 67, 89, 45, 90, 22, 70, 58])

passed = marks[marks >= 50]
failed = marks[marks < 50]

print("Passed Marks:", passed)
print("Failed Marks:", failed)

print("Number of Passed Students:", len(passed))
print("Number of Failed Students:", len(failed))

Passed Marks: [67 89 90 70 58]
Failed Marks: [35 45 22]
Number of Passed Students: 5
Number of Failed Students: 3


#Question 1 — Array Creation

NumPy ka use karke ye array banao:
```
[10, 20, 30, 40, 50]
```


In [ ]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers)

[10 20 30 40 50]


#Question 2 — Array Properties

 Array:
```
numbers = np.array([10, 20, 30, 40, 50])
```
Find karo:
- shape
- size
- dtype
- ndim




In [ ]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print("Dimensions:", numbers.ndim)
print("Shape:", numbers.shape)
print("Size:", numbers.size)
print("Data Type:", numbers.dtype)

Dimensions: 1
Shape: (5,)
Size: 5
Data Type: int64


#Question 3 — Indexing

Array:
```
numbers = np.array([15, 25, 35, 45, 55, 65])
```
Print:

- First value

- Third value

- Last value

In [ ]:
import numpy as np

numbers = np.array([15, 25, 35, 45, 55, 65])

print("First:", numbers[0])
print("Third:", numbers[2])
print("Last:", numbers[-1])

First: 15
Third: 35
Last: 65


#Question 4 — Slicing

Array:
```
numbers = np.array([10, 20, 30, 40, 50, 60])
````

```
20 30 40
```

In [ ]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50, 60])

print(numbers[1:4])

[20 30 40]


#Question 5 — Vectorized Operations

Array:
```
numbers = np.array([10, 20, 30, 40])
```
Find :

-  value mein 5 *add*
-  value mein 2 multiply
-  value mein 3 subtract
-  value ko 2 se divide

In [ ]:
import numpy as np

numbers = np.array([10, 20, 30, 40])

print("Add 5:", numbers + 5)
print("Multiply by 2:", numbers * 2)
print("Subtract 3:", numbers - 3)
print("Divide by 2:", numbers / 2)

Add 5: [15 25 35 45]
Multiply by 2: [20 40 60 80]
Subtract 3: [ 7 17 27 37]
Divide by 2: [ 5. 10. 15. 20.]


# Question 6 — Two Arrays

Do arrays :
```
a = [10, 20, 30]
b = [2, 4, 6]
```
Find :

- a + b
- a - b
- a * b
- a / b

In [ ]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([2, 4, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [12 24 36]
Subtraction: [ 8 16 24]
Multiplication: [ 20  80 180]
Division: [5. 5. 5.]


#Question 7 — Mathematical Functions

Array:
```
numbers = np.array([4, 9, 16, 25])
```
Find :

- Square root
- Square/power of 2

In [ ]:
import numpy as np

numbers = np.array([4, 9, 16, 25])

print("Square Root:", np.sqrt(numbers))
print("Power 2:", np.power(numbers, 2))

Square Root: [2. 3. 4. 5.]
Power 2: [ 16  81 256 625]


#Question 8 — Aggregation

Array:
```
marks = np.array([55, 70, 85, 90, 65])
```
Find :

- Total marks
- Average
- Highest marks
- Lowest marks
- Median

In [ ]:
import numpy as np

marks = np.array([55, 70, 85, 90, 65])

print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))
print("Lowest:", np.min(marks))
print("Median:", np.median(marks))

Total: 365
Average: 73.0
Highest: 90
Lowest: 55
Median: 70.0


#Question 9 — Condition

Array:
```
marks = np.array([30, 45, 60, 75, 90, 35])
```
marks:
```
>= 50
```

In [ ]:
import numpy as np

marks = np.array([30, 45, 60, 75, 90, 35])

print(marks >= 50)

[False False  True  True  True False]


#Question 10 — Filtering

array:
```
marks = np.array([30, 45, 60, 75, 90, 35])
```
passed marks print .
```
Passing marks = 50
```

In [ ]:
import numpy as np

marks = np.array([30, 45, 60, 75, 90, 35])

passed = marks[marks >= 50]

print("Passed Marks:", passed)

#Question 11 — Failed Students

Array:
```
marks = np.array([30, 45, 60, 75, 90, 35])
```
failed marks print.
````
Passing marks = 50
````

In [ ]:
import numpy as np

marks = np.array([30, 45, 60, 75, 90, 35])

failed = marks[marks < 50]

print("Failed Marks:", failed)

#Question 12 — 2D Array

2D array:
```
10 20 30
40 50 60
70 80 90
```
- 50 print karo
- 90 print karo
- ndim print karo
- shape print karo
- size print karo

In [ ]:
import numpy as np

data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("50:", data[1, 1])
print("90:", data[2, 2])

print("Dimensions:", data.ndim)
print("Shape:", data.shape)
print("Size:", data.size)

#Question 13 — Reshape

Array:
```
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8])
```
Isko:
```
4 rows
2 columns
```
reshape .

In [ ]:
import numpy as np

numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8])

new_array = numbers.reshape(4, 2)

print(new_array)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#Question 14 — Flatten

 array:
```
1 2 3
4 5 6
```
 1D array mein convert.
```
Expected:
[1 2 3 4 5 6]
```

In [ ]:
import numpy as np

data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(data.flatten())

[1 2 3 4 5 6]


#Question 15 — zeros, ones, arange

3 arrays :
```
1. 5 zeros
2. 5 ones
3. 1 se 10
```

In [ ]:
import numpy as np

print("Zeros:")
print(np.zeros(5))

print("Ones:")
print(np.ones(5))

print("Numbers:")
print(np.arange(1, 11))

Zeros:
[0. 0. 0. 0. 0.]
Ones:
[1. 1. 1. 1. 1.]
Numbers:
[ 1  2  3  4  5  6  7  8  9 10]


#Question 16 — Random Numbers

NumPy se 10 random marks generate karo jo 40 se 100 ke darmiyan hon.

find :

- Average
- Maximum
- Minimum

In [ ]:
import numpy as np

marks = np.random.randint(40, 101, 10)

print("Random Marks:", marks)

print("Average:", np.mean(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))

# Student Marks Analyzer

Now we will use different NumPy concepts in one small program.

## Problem

We have marks of different students.

We want to find:

- Average marks
- Highest marks
- Lowest marks
- Total passed students
- Total failed students

In [ ]:
import numpy as np

marks = np.array([45, 78, 90, 32, 67, 88, 55, 40, 95, 28])

print("Student Marks:")
print(marks)

print("\nAverage Marks:", np.mean(marks))
print("Highest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))

passed = marks[marks >= 50]
failed = marks[marks < 50]

print("\nPassed Students Marks:")
print(passed)

print("Failed Students Marks:")
print(failed)

print("\nTotal Passed:", len(passed))
print("Total Failed:", len(failed))

Student Marks:
[45 78 90 32 67 88 55 40 95 28]

Average Marks: 61.8
Highest Marks: 95
Lowest Marks: 28

Passed Students Marks:
[78 90 67 88 55 95]
Failed Students Marks:
[45 32 40 28]

Total Passed: 6
Total Failed: 4
